theme = "showfolio"
languageCode = "en-us"
baseurl = "https://motocarota.art"
title = "Motocarota.art"

[params]
  name = "Motocarota"
  description = "Comic Artist / Illustrator."
  author = "Simone Poggi"
  authorEmail = "motocarota@gmail.com"
  authorImage = "/motocarota-logo.png"
  autoDarkMode = true
  mixpanel = "aed574b45bdbfa6cf70ba9ebcf149503"

  copyright = "All images are Copyright ©2022 Simone Poggi, All Rights Reserved"
  favicon = "favicon.ico"

[params.homepage]
  title = "Hey! I'm Motocarota"
  tagline = "Comic Artist and Illustrator"
  description = ""

[[params.homepage.gallery]]
  img = "/001-aarakocra.jpg"

[[params.homepage.gallery]]
  img = "/aoqtd-en-01_026.jpg"

[[params.homepage.gallery]]
  img = "/Jumong.jpg"

[[params.homepage.gallery]]
  img = "/002-aboleth.jpg"

[[params.homepage.gallery]]
  img = "/aoqtd-d00_004.jpg"

[[params.homepage.gallery]]
  img = "/Freya.jpg"

[[params.homepage.gallery]]
  img = "/Rick.jpg"

[[params.homepage.gallery]]
  img = "/Skate.jpg"

[[params.homepage.gallery]]
  img = "/tivale.jpg"


[params.homepage.resume]
  skills = ["Procreate", "Clip Studio Paint", "Pencil & Traditional Ink"]

[[params.homepage.resume.courses]]
  name = "Universita' degli studi di Genova"
  provider = "Degree in Computer Science"
  duration = "Sept 2003 - Nov 2009"

[[params.homepage.resume.courses]]
  name = "Scuola Chiavarese del Fumetto"
  duration = "Oct 2011 - Jan 2015"

[params.homepage.social]
  twitter = "https://twitter.com/motocarota"
  instagram = "https://instagram.com/motocarota"
  github = "https://github.com/motocarota"
  reddit = "https://reddit.com/u/motocarota"
  artstation = "https://artstation.com/motocarota"
  telegram = "https://t.me/motocarota"
  patreon = "https://patreon.com/motocarota"
  linktree = "https://linktree.com/motocarota"

[build]
  writeStats = false

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
