theme = "showfolio"
languageCode = "en-us"
baseurl = "https://example.com"
title = "Showfolio Theme"


[params]
  name = "Showfolio Theme"
  description = "Modern portfolio theme for your Hugo site."
  author = "John Doe"
  authorEmail = "name@example.com"
  authorImage = "/photo.png"
  autoDarkMode = true

  copyright = "Copyright © 2021 - John Doe · All rights reserved"
  favicon = "favicon.ico"

[params.homepage]
  title = "Hey 👋 I'm John Doe"
  tagline = "UX Designer and Product Lead"
  description = "Develop functional user interfaces and provide a valuable experience to customers."
  contact = "https://twitter.com/"

[params.homepage.codepen]
  username = "apvarun"
  pens = ["MQaRKL", "RxodrP", "BmXGdm", "wdVypQ"]

[params.homepage.resume]
  skills = ["Visual Design", "Product Development"]

[[params.homepage.resume.work]]
  name = "Google"
  role = "Product Engineer"
  duration = "Nov 2019 - Apr 2021"

[[params.homepage.resume.work]]
  name = "Amazon"
  role = "Sr. UX Designer"
  duration = "Jan 2016 - Oct 2019"

[[params.homepage.resume.courses]]
  name = "Design Principles"
  provider = "UX Academy"
  duration = "Nov 2019 - Jan 2020"

[params.homepage.social]
  twitter = "https://twitter.com/"
  linkedin = "https://linkedin.com/in/"
  github = "https://github.com/"
  medium = "https://medium.com/"
  reddit = "https://reddit.com/"
  dribbble = "https://dribbble.com/"

[build]
  writeStats = true

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
